language: python

python:
  - "3.12"
  - "3.11"
  - "3.10"
  - "3.9"
  - "3.8"
  - "3.7"

install:
  - pip install setuptools
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install -e .


script:
  - pytest 

script: pytest --cov=clickupython tests/

after_success:
  - coveralls